### ISSUE TITLE
'Display associations in entries table' is always checked

### ISSUE THREAD

**Issue by nathanhornby** [symphonists/association_field#13]
I've been finding that 'Display associations in entries table' is always checked. i.e. even if the actual field's settings have it set to 'No', it will still be checked when editing the section.

This means if you have an association field with that option unchecked, and edit your section, you need to uncheck it again before saving else it'll change itself.

Hopefully the above makes sense, I wonder if it's related to Jen's issue https://github.com/symphonists/association_field/issues/6? That seems to state that the option isn't saved - for me it is saving, it's just that it's always rendered as checked.

**Comment by brendo** [comment]
This should be resolved with the release of 2.6.1
