### ISSUE TITLE
Styling issues for settings panel

### ISSUE THREAD

**Issue by designermonkey** [symphonists/association_field#14]
<del>When using this field with the order_entries field in the section editor,</del> the association field settings UI completely breaks and is unusable.

Edit: This just breaks when saving a section that contains an Association field.

**Comment by jonmifsud** [comment]
@designermonkey is this still an issue? I can't seem to replicate on Chrome on OS X Yosemite.

**Comment by brendo** [comment]
@jonmifsud I believe this was fixed with symphonycms/symphony-2#2260
