### ISSUE TITLE
Allow filtering with proper values in Symphony 2.6.0 filterring

### ISSUE THREAD

**Issue by animaux** [symphonists/association_field#17]
As far as I understand [this commit](https://github.com/symphonycms/selectbox_link_field/commit/780d775d14e22ec8c5db1e1c9f76bd32a9567441) makes it possible for `SBL` fields to be filtered by their linked title/etc. rather than ID only.

Can this be equally applied to the `association_field`?

**Comment by jonmifsud** [comment]
@animaux doesn't this already work out of the box? I am filtering in the backend using the values within the associations. And as far as I'm aware backend/front-end filtering should use the same logic.

The one problem I'm aware  of is when used in conjunction with the pre-populate field (which expects an ID) thus it breaks. Planning to have a look at it though tight on time right now.

**Comment by animaux** [comment]
@jonmifsud No, doesn’t work for me. Only by using IDs which is impractical for customers.
