### ISSUE TITLE
Not working on Symphony Version: 2.6.2

### ISSUE THREAD

**Issue by manuelro** [symphonists/association_field#20]
I can install enable/disable the extension, but once I create a new field for a section, the editing screen for the particular section just throws a blank page.

See my logs:

```
[Mon Aug 10 12:40:46.719880 2015] [:error] [pid 909] [client 127.0.0.1:54986] PHP Fatal error:  
Call to undefined method FieldAssociation::appendAssociationInterfaceSelect() 
in /www/sites/crpn/wwwroot/extensions/association_field/fields/field.association.php 
on line 502, referer: http://crpn.dev/symphony/publish/paquetes/edit/817/
```

**Comment by nilshoerrmann** [comment]
This field is not compatible with Symphony 2.3 – the latest release requires requires Symphony 2.5, see https://github.com/symphonists/association_field/blob/master/extension.meta.xml.

**Comment by manuelro** [comment]
I didn't mean 2.3 but 2.6.2.

**Comment by brendo** [comment]
Please double check your Symphony files are up to date. The function exists [in Symphony 2.6.2](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.field.php#L679) inside the `lib/toolkit/class.field.php`

**Comment by jurajkapsz** [comment]
This versions works fine. Maybe we can close this issue? @manuelro
