### ISSUE TITLE
Migration from SBL and SSM

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/association_field#3]
See hananils/association_ui_selector#5.

**Comment by bzerangue** [comment]
Is it possible to add a migration script from subsectionmanager field to association field like @nilshoerrmann did when he deprecated the mediathek field where you could migrate from mediathek field to the subsectionmanager field? 

This would be great feature to make the migration process easier. Especially when so many of us used and relied on the subsectionmanager field.

**Comment by nilshoerrmann** [comment]
It would be possible to do this to migrate from SBL to AF, but a direct upgrade from SSM to AF is not possible due to the different feature set (this was different when Mediathek became Subsection Manager). For the backend, you'll have to replace custom captions manually and you'll have to work around the lack of content filtering (see #12). On the frontend, your XML will change because AF doesn't support nested output out of the box – so you'll have to migrate to Association Output on that side.

Formalising the guidelines from this thread and adding them to the readme would be the best we can do.

**Comment by bzerangue** [comment]
Ok. Thank you

—

**Comment by tonyarnold** [comment]
Sorry to resurrect an old issue, but I'm making this move now. Can I select more than one "Value" for an association? Say I have a description and a file in my associated section — can I select both of them? I'm guessing there are some limitations here I'm unaware of.

**Comment by animaux** [comment]
@tonyarnold I am guessing you mean if it possible to show the description and linked file of an associated section in the selector interface? If that’s what you mean the answer is: yes, by using a `reflection field` to compile the info you need, and select this field in the association field that links to the section.

Have a look [here](https://github.com/hananils/association_ui_selector#user-content-custom-captions).
