### ISSUE TITLE
Clean-up

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/association_field#5]
Old code from SBL, things related to backwards-compatibility etc. should be removed.

@brendo: Would you mind having a look, if there are things we can simplify? Thanks!

**Comment by twiro** [comment]
> _It would be great, if we could tackle this before the release of Symphony 2.6 – at least all bug fixes to SBL should be merged in._

BTW: I created an "SBL"-Branch of the extension, that backports all additions to SBL (that haven't been included in this repo yet) and follows the versioning/naming-scheme of SBL:

 - https://github.com/twiro/association_field/tree/sbl

I submitted the commits one by one and referenced to the original ones:

 - https://github.com/twiro/association_field/commits/sbl

As long as SBL and Association Field coexist (which in my opinion is not a good solution in the long run) it might be helpful to couple updates & versions of both extensions (except for enhanced features of the association field).

**Comment by nilshoerrmann** [comment]
Cool. 

I'm not sure how the team is going to handle SBL and AF in the future – or if it's going to be handled at all (well the idea one and a half year ago was to deprecate the first and move on with the second extension). Maybe @brendo can chime in here. 

[Version 1.0.0](https://github.com/symphonists/association_field/releases/tag/1.0.0) is just a summary of the open changes and fixes.

**Comment by twiro** [comment]
Moved the discussion about my proposal to a separate issue:

- https://github.com/symphonists/association_field/issues/19

> _I'm not sure how the team is going to handle SBL and AF in the future – or if it's going to be handled at all (well the idea one and a half year ago was to deprecate the first and move on with the second extension)._

Well... while it's surely not perfect that a clear cut was missed right at the start and association field wasn't treated as the successor/replacement for **SBL** I think as of now it wouldn't make much sense to change this before the next major relase of Symphony.

And I somehow feel that it's partly my fault as [I insisted on changing the name](http://www.getsymphony.com/discuss/thread/106489/#position-2) of the extension ;)

Will probably open a separate issue for generally discussing this topic the next days.
